version: '3.5'
services:
  web:
    image: web
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:9000"
    volumes:
      - .:/app
      - /app/node_modules
